module.exports = {

  USER_FOLLOWED:
    "USER_FOLLOWED",

  FRIEND_REQUEST_SENT:
    "FRIEND_REQUEST_SENT",

  FRIEND_REQUEST_ACCEPTED:
    "FRIEND_REQUEST_ACCEPTED",

  USER_BLOCKED:
    "USER_BLOCKED",

  USER_MUTED:
    "USER_MUTED",

  USER_SUBSCRIBED:
    "USER_SUBSCRIBED",
    FRIEND_REQUEST_SENT: "FRIEND_REQUEST_SENT",
  FRIEND_REQUEST_CANCELLED: "FRIEND_REQUEST_CANCELLED",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  FRIEND_REQUEST_REJECTED: "FRIEND_REQUEST_REJECTED",
  FRIEND_REMOVED: "FRIEND_REMOVED"
};