module.exports = {

  AD_CREATED: "AD_CREATED",
  AD_UPDATED: "AD_UPDATED",
  AD_PAUSED: "AD_PAUSED",
  AD_RESUMED: "AD_RESUMED",
  AD_COMPLETED: "AD_COMPLETED",
  AD_CLICKED: "AD_CLICKED",
  AD_IMPRESSION: "AD_IMPRESSION"

};