module.exports = {

  APPLICATION_CREATED:
  "APPLICATION_CREATED",

  APPLICATION_UPDATED:
  "APPLICATION_UPDATED",

  APPLICATION_ACCEPTED:
  "APPLICATION_ACCEPTED",

  APPLICATION_REJECTED:
  "APPLICATION_REJECTED",

  APPLICATION_WITHDRAWN:
  "APPLICATION_WITHDRAWN"
};