module.exports = {

  CREATED: "CREATOR_STUDIO_CREATED",
  UPDATED: "CREATOR_STUDIO_UPDATED",
  SCHEDULED: "CREATOR_STUDIO_SCHEDULED",
  PUBLISHED: "CREATOR_STUDIO_PUBLISHED",
  FAILED: "CREATOR_STUDIO_FAILED",
  DELETED: "CREATOR_STUDIO_DELETED"

};