module.exports = {

  WATCHPARTY_CREATED:
  "WATCHPARTY_CREATED",

  WATCHPARTY_STARTED:
  "WATCHPARTY_STARTED",

  WATCHPARTY_JOINED:
  "WATCHPARTY_JOINED",

  WATCHPARTY_LEFT:
  "WATCHPARTY_LEFT",

  WATCHPARTY_ENDED:
  "WATCHPARTY_ENDED",

  WATCHPARTY_DELETED:
  "WATCHPARTY_DELETED"
};