module.exports = {
  // USER
  USER_REGISTERED: "USER_REGISTERED",
  USER_UPDATED: "USER_UPDATED",

  // POST
  POST_CREATED: "POST_CREATED",
  POST_LIKED: "POST_LIKED",

  // REEL
  REEL_CREATED: "REEL_CREATED",

  // STORY
  STORY_CREATED: "STORY_CREATED",
  STORY_EXPIRED: "STORY_EXPIRED",

  // PODCAST
  PODCAST_CREATED: "PODCAST_CREATED",
  EPISODE_PUBLISHED: "EPISODE_PUBLISHED",

  // MESSAGE
  MESSAGE_SENT: "MESSAGE_SENT",

  // WALLET
  WALLET_CREDITED: "WALLET_CREDITED",
  WALLET_DEBITED: "WALLET_DEBITED",

  // SUBSCRIPTION
  SUBSCRIPTION_PURCHASED: "SUBSCRIPTION_PURCHASED",

  // MARKETPLACE
  MARKETPLACE_CREATED: "MARKETPLACE_CREATED",

  // HIRE
  CREATOR_HIRE_CREATED: "CREATOR_HIRE_CREATED",

  // BUSINESS
  BUSINESS_FIND_CREATED: "BUSINESS_FIND_CREATED",

  // ADMIN
  ADMIN_ACTION: "ADMIN_ACTION"
};