module.exports = {
  FREE_MEMBER: "FREE_MEMBER",
  FREE_CREATOR: "FREE_CREATOR",
  FREE_BUSINESS: "FREE_BUSINESS",

  MEMBER_BASIC: "MEMBER_BASIC",
  MEMBER_PLUS: "MEMBER_PLUS",

  CREATOR_BASIC: "CREATOR_BASIC",
  CREATOR_PLUS: "CREATOR_PLUS",
  CREATOR_PRO: "CREATOR_PRO",

  BUSINESS_BASIC: "BUSINESS_BASIC",
  BUSINESS_PRO: "BUSINESS_PRO",
  BUSINESS_ENTERPRISE: "BUSINESS_ENTERPRISE"
};