module.exports = {
  WALLET_CREATED:
    "WALLET_CREATED",

  FUNDS_DEPOSITED:
    "FUNDS_DEPOSITED",

  FUNDS_WITHDRAWN:
    "FUNDS_WITHDRAWN",

  TRANSACTION_CREATED:
    "TRANSACTION_CREATED",

  TRANSACTION_COMPLETED:
    "TRANSACTION_COMPLETED",

  TRANSACTION_FAILED:
    "TRANSACTION_FAILED"
};