module.exports = {
  // Conversation Lifecycle
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATION_UPDATED: "CONVERSATION_UPDATED",
  CONVERSATION_DELETED: "CONVERSATION_DELETED",
  CONVERSATION_ARCHIVED: "CONVERSATION_ARCHIVED",
  CONVERSATION_UNARCHIVED: "CONVERSATION_UNARCHIVED",

  // Participants
  PARTICIPANT_ADDED: "PARTICIPANT_ADDED",
  PARTICIPANT_REMOVED: "PARTICIPANT_REMOVED",
  PARTICIPANT_LEFT: "PARTICIPANT_LEFT",
  PARTICIPANT_PROMOTED: "PARTICIPANT_PROMOTED",
  PARTICIPANT_DEMOTED: "PARTICIPANT_DEMOTED",

  // Messages
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_EDITED: "MESSAGE_EDITED",
  MESSAGE_DELETED: "MESSAGE_DELETED",
  MESSAGE_REACTED: "MESSAGE_REACTED",
  MESSAGE_READ: "MESSAGE_READ",
  MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
  MESSAGE_FORWARDED: "MESSAGE_FORWARDED",
  MESSAGE_REPLIED: "MESSAGE_REPLIED",

  // Typing
  USER_TYPING: "USER_TYPING",
  USER_STOPPED_TYPING: "USER_STOPPED_TYPING",

  // Presence
  USER_ONLINE: "USER_ONLINE",
  USER_OFFLINE: "USER_OFFLINE",

  // Calls
  CALL_STARTED: "CALL_STARTED",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_REJECTED: "CALL_REJECTED",
  CALL_ENDED: "CALL_ENDED",

  // Attachments
  ATTACHMENT_UPLOADED: "ATTACHMENT_UPLOADED",
  ATTACHMENT_DELETED: "ATTACHMENT_DELETED",

  // Moderation
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  CONVERSATION_REPORTED: "CONVERSATION_REPORTED"
};