module.exports = {

  SUBSCRIPTION_CREATED:
    "SUBSCRIPTION_CREATED",

  SUBSCRIPTION_UPGRADED:
    "SUBSCRIPTION_UPGRADED",

  SUBSCRIPTION_CANCELLED:
    "SUBSCRIPTION_CANCELLED",

    
  SUBSCRIPTION_RENEWED:
   "SUBSCRIPTION_RENEWED"

};