module.exports = {

  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  TOKEN_PURCHASED: "TOKEN_PURCHASED",
  VOUCHER_REDEEMED: "VOUCHER_REDEEMED",

  SUBSCRIPTION_PAID: "SUBSCRIPTION_PAID",
  MARKETPLACE_PAID: "MARKETPLACE_PAID"

};