module.exports = {

  ADMIN_DASHBOARD_VIEWED:
  "ADMIN_DASHBOARD_VIEWED",

  USER_SUSPENDED:
  "USER_SUSPENDED",

  USER_UNSUSPENDED:
  "USER_UNSUSPENDED",

  USER_ROLE_UPDATED:
  "USER_ROLE_UPDATED",

  ADMIN_ANNOUNCEMENT_CREATED:
  "ADMIN_ANNOUNCEMENT_CREATED"

};