module.exports = {
  STORY_CREATED: "STORY_CREATED",
  STORY_VIEWED: "STORY_VIEWED",
  STORY_REACTED: "STORY_REACTED",
  STORY_REPLIED: "STORY_REPLIED",
  STORY_EXPIRED: "STORY_EXPIRED",
  STORY_DELETED: "STORY_DELETED"
};