module.exports = {

  VERIFICATION_SUBMITTED:
  "VERIFICATION_SUBMITTED",

  VERIFICATION_APPROVED:
  "VERIFICATION_APPROVED",

  VERIFICATION_REJECTED:
  "VERIFICATION_REJECTED",

  VERIFICATION_CANCELLED:
  "VERIFICATION_CANCELLED"

};