module.exports = {
  EPISODE_CREATED: "EPISODE_CREATED",
  EPISODE_PUBLISHED: "EPISODE_PUBLISHED",
  EPISODE_PLAYED: "EPISODE_PLAYED",
  EPISODE_VIEWED: "EPISODE_VIEWED",
  EPISODE_LIKED: "EPISODE_LIKED",
  EPISODE_SHARED: "EPISODE_SHARED"
};