module.exports = {

  BUSINESS_FIND_CREATED:
  "BUSINESS_FIND_CREATED",

  BUSINESS_FIND_UPDATED:
  "BUSINESS_FIND_UPDATED",

  BUSINESS_FIND_APPLIED:
  "BUSINESS_FIND_APPLIED",

  BUSINESS_FIND_APPROVED:
  "BUSINESS_FIND_APPROVED",

  BUSINESS_FIND_REJECTED:
  "BUSINESS_FIND_REJECTED",

  BUSINESS_FIND_DELETED:
  "BUSINESS_FIND_DELETED"
};