module.exports = {

  MARKETPLACE_CREATED:
  "MARKETPLACE_CREATED",

  MARKETPLACE_UPDATED:
  "MARKETPLACE_UPDATED",

  MARKETPLACE_DELETED:
  "MARKETPLACE_DELETED",

  MARKETPLACE_APPLIED:
  "MARKETPLACE_APPLIED"
};