module.exports = {

  SUPPORT_TICKET_CREATED:
  "SUPPORT_TICKET_CREATED",

  SUPPORT_TICKET_ASSIGNED:
  "SUPPORT_TICKET_ASSIGNED",

  SUPPORT_TICKET_UPDATED:
  "SUPPORT_TICKET_UPDATED",

  SUPPORT_TICKET_RESOLVED:
  "SUPPORT_TICKET_RESOLVED",

  SUPPORT_TICKET_CLOSED:
  "SUPPORT_TICKET_CLOSED"

};