module.exports = {

  POST_CREATED:
    "POST_CREATED",

  POST_UPDATED:
    "POST_UPDATED",

  POST_DELETED:
    "POST_DELETED",

  POST_LIKED:
    "POST_LIKED",

  POST_UNLIKED:
    "POST_UNLIKED",

  POST_COMMENTED:
    "POST_COMMENTED",

  POST_COMMENT_DELETED:
    "POST_COMMENT_DELETED",

  POST_SHARED:
    "POST_SHARED",

  POST_SAVED:
    "POST_SAVED",

  POST_UNSAVED:
    "POST_UNSAVED",

  POST_VIEWED:
    "POST_VIEWED",

  POST_REPORTED:
    "POST_REPORTED",

  
  POST_COMMENT_LIKED: "POST_COMMENT_LIKED",
  POST_COMMENT_UNLIKED: "POST_COMMENT_UNLIKED",
  POST_COMMENT_EDITED: "POST_COMMENT_EDITED",
  POST_COMMENT_REPLIED: "POST_COMMENT_REPLIED",
  POST_COMMENT_DELETED: "POST_COMMENT_DELETED"

};