module.exports = {
  // Account
  MONETIZATION_ENABLED: "MONETIZATION_ENABLED",
  MONETIZATION_DISABLED: "MONETIZATION_DISABLED",
  MONETIZATION_APPROVED: "MONETIZATION_APPROVED",
  MONETIZATION_REJECTED: "MONETIZATION_REJECTED",

  // Wallet
  WALLET_CREATED: "WALLET_CREATED",
  WALLET_UPDATED: "WALLET_UPDATED",
  WALLET_CREDITED: "WALLET_CREDITED",
  WALLET_DEBITED: "WALLET_DEBITED",
  WALLET_FROZEN: "WALLET_FROZEN",
  WALLET_UNFROZEN: "WALLET_UNFROZEN",

  // Revenue
  REVENUE_EARNED: "REVENUE_EARNED",
  REVENUE_ADDED: "REVENUE_ADDED",
  REVENUE_REVERSED: "REVENUE_REVERSED",
  REVENUE_SETTLED: "REVENUE_SETTLED",

  // Ads
  AD_REVENUE_EARNED: "AD_REVENUE_EARNED",
  AD_IMPRESSION_RECORDED: "AD_IMPRESSION_RECORDED",
  AD_CLICK_RECORDED: "AD_CLICK_RECORDED",

  // Creator Fund
  CREATOR_FUND_REWARD: "CREATOR_FUND_REWARD",

  // Marketplace
  MARKETPLACE_REVENUE: "MARKETPLACE_REVENUE",

  // Creator Hire
  CREATOR_HIRE_REVENUE: "CREATOR_HIRE_REVENUE",

  // Business
  BUSINESS_PROMOTION_REVENUE: "BUSINESS_PROMOTION_REVENUE",

  // Podcast
  PODCAST_REVENUE: "PODCAST_REVENUE",

  // Reels
  REEL_REVENUE: "REEL_REVENUE",

  // Videos
  VIDEO_REVENUE: "VIDEO_REVENUE",

  // Stories
  STORY_REVENUE: "STORY_REVENUE",

  // Watch Parties
  WATCH_PARTY_REVENUE: "WATCH_PARTY_REVENUE",

  // Live Streams
  LIVE_REVENUE: "LIVE_REVENUE",
  LIVE_GIFT_RECEIVED: "LIVE_GIFT_RECEIVED",
  LIVE_STAR_RECEIVED: "LIVE_STAR_RECEIVED",
  LIVE_TIP_RECEIVED: "LIVE_TIP_RECEIVED",

  // Tips
  TIP_RECEIVED: "TIP_RECEIVED",

  // Stars
  STAR_RECEIVED: "STAR_RECEIVED",

  // Gifts
  GIFT_RECEIVED: "GIFT_RECEIVED",

  // Memberships
  MEMBERSHIP_PURCHASED: "MEMBERSHIP_PURCHASED",
  MEMBERSHIP_RENEWED: "MEMBERSHIP_RENEWED",
  MEMBERSHIP_CANCELLED: "MEMBERSHIP_CANCELLED",

  // Subscriptions
  SUBSCRIPTION_PURCHASED: "SUBSCRIPTION_PURCHASED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",

  // Affiliate
  AFFILIATE_COMMISSION: "AFFILIATE_COMMISSION",

  // Sponsors
  SPONSORSHIP_PAID: "SPONSORSHIP_PAID",

  // Withdrawals
  WITHDRAWAL_REQUESTED: "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_APPROVED: "WITHDRAWAL_APPROVED",
  WITHDRAWAL_REJECTED: "WITHDRAWAL_REJECTED",
  WITHDRAWAL_COMPLETED: "WITHDRAWAL_COMPLETED",

  // Taxes
  TAX_DOCUMENT_SUBMITTED: "TAX_DOCUMENT_SUBMITTED",
  TAX_DOCUMENT_APPROVED: "TAX_DOCUMENT_APPROVED",

  // Admin
  ADMIN_REVENUE_ADJUSTMENT: "ADMIN_REVENUE_ADJUSTMENT",
  ADMIN_BONUS_GRANTED: "ADMIN_BONUS_GRANTED"
};