const plans = require("../config/plans.config");

const FEATURES = {

    // ===========================
    // GENERAL
    // ===========================

    VIEW_FEED: "VIEW_FEED",
    VIEW_REELS: "VIEW_REELS",
    VIEW_STORIES: "VIEW_STORIES",
    VIEW_PODCASTS: "VIEW_PODCASTS",
    VIEW_WATCH_PARTIES: "VIEW_WATCH_PARTIES",
ADVERTISEMENT_VIEW: "ADVERTISEMENT_VIEW",
    VIEW_CREATOR_HUB: "VIEW_CREATOR_HUB",
    VIEW_BUSINESS_HUB: "VIEW_BUSINESS_HUB",
    VIEW_MARKETPLACE: "VIEW_MARKETPLACE",
    VIEW_SOCIAL_SOCIALS: "VIEW_SOCIAL_SOCIALS",
APPLICATION_VIEW: "APPLICATION_VIEW",
    VIEW_WALLET: "VIEW_WALLET",
    VIEW_SUBSCRIPTIONS: "VIEW_SUBSCRIPTIONS",
    VIEW_MONETIZATION: "VIEW_MONETIZATION",
    VIEW_SUPPORT: "VIEW_SUPPORT",

    SEARCH: "SEARCH",
    DISCOVER: "DISCOVER",
    TRENDING: "TRENDING",
    RECOMMENDATIONS: "RECOMMENDATIONS",

    // CONTENT

    CREATE_POST: "CREATE_POST",
    EDIT_POST: "EDIT_POST",
    DELETE_POST: "DELETE_POST",

    CREATE_REEL: "CREATE_REEL",
    EDIT_REEL: "EDIT_REEL",
    DELETE_REEL: "DELETE_REEL",

    CREATE_STORY: "CREATE_STORY",
    EDIT_STORY: "EDIT_STORY",
    DELETE_STORY: "DELETE_STORY",

    COMMENT: "COMMENT",
    LIKE: "LIKE",
    SHARE: "SHARE",
    FOLLOW: "FOLLOW",
    SEND_FRIEND_REQUEST: "SEND_FRIEND_REQUEST",
ACCEPT_FRIEND_REQUEST: "ACCEPT_FRIEND_REQUEST",
REJECT_FRIEND_REQUEST: "REJECT_FRIEND_REQUEST",
CANCEL_FRIEND_REQUEST: "CANCEL_FRIEND_REQUEST",
UNFRIEND: "UNFRIEND",
    POST_REPORT: "POST_REPORT",
    POST_SAVE: "POST_SAVE",
    MEDIA_UPLOAD: "MEDIA_UPLOAD",

    // MESSAGES

    CONVERSATION_READ: "CONVERSATION_READ",
    CONVERSATION_CREATE: "CONVERSATION_CREATE",
    // WALLET

    WALLET: "WALLET",
    RECEIVE_PAYMENTS: "RECEIVE_PAYMENTS",
    WITHDRAW: "WITHDRAW",

    // MARKETPLACE
MARKETPLACE_CREATE: "MARKETPLACE_CREATE",
    MARKETPLACE_BUY: "MARKETPLACE_BUY",
    MARKETPLACE_SELL: "MARKETPLACE_SELL",

    // CREATOR

    CREATOR_HIRE_CREATE: "CREATOR_HIRE_CREATE",
CREATOR_HIRE_VIEW: "VIEW_CREATOR_HUB",
CREATOR_HIRE_APPLY: "CREATOR_HIRE_APPLY",
CREATOR_HIRE_EDIT: "CREATOR_HIRE_EDIT",
CREATOR_HIRE_DELETE: "CREATOR_HIRE_DELETE",
APPLICATION_UPDATE: "APPLICATION_UPDATE",
APPLICATION_CREATE: "APPLICATION_CREATE",
SPONSORSHIP_APPLY: "SPONSORSHIP_APPLY",
    GO_LIVE: "GO_LIVE",
    LIVE_720: "LIVE_720",
    LIVE_1080: "LIVE_1080",
    LIVE_4K: "LIVE_4K",

    PODCAST_STUDIO: "PODCAST_STUDIO",
    PODCAST_CREATE: "PODCAST_CREATE",
    EPISODE_CREATE: "EPISODE_CREATE",
    PODCAST_DELETE: "PODCAST_DELETE",
    EPISODE_DELETE: "EPISODE_DELETE",
    VIEW_PODCASTS_HUB: "VIEW_PODCASTS_HUB",
VIEW_EPISODES_HUB: "VIEW_EPISODES_HUB",


    // BUSINESS

    BUSINESS_PROFILE: "BUSINESS_PROFILE",
    BUSINESS_STUDIO: "BUSINESS_STUDIO",
    BUSINESS_ANALYTICS: "BUSINESS_ANALYTICS",
    PODCAST_CREATE: "PODCAST_CREATE",
     EPISODE_CREATE: "EPISODE_CREATE",
     PODCAST_DELETE: "PODCAST_DELETE",
    EPISODE_DELETE: "EPISODE_DELETE",
     VIEW_PODCASTS_HUB: "VIEW_PODCASTS_HUB",
VIEW_EPISODES_HUB: "VIEW_EPISODES_HUB",
 ADVERTISEMENT_CREATE: "ADVERTISEMENT_CREATE",
SPONSORSHIP_CREATE: "SPONSORSHIP_CREATE",
 BUSINESSFIND_CREATE: "BUSINESSFIND_CREATE",
 SPONSORSHIP_VIEW_APPLICATIONS: "SPONSORSHIP_VIEW_APPLICATIONS",
  SPONSORSHIP_ACCEPT: "SPONSORSHIP_ACCEPT",
SPONSORSHIP_REJECT: "SPONSORSHIP_REJECT",
    CRM: "CRM",
    INVENTORY: "INVENTORY",
    ORDERS: "ORDERS",
    BOOKINGS: "BOOKINGS",

    PRODUCTS: "PRODUCTS",
    SERVICES: "SERVICES",

    LOYALTY: "LOYALTY",
    COUPONS: "COUPONS",

    // AI

    AI_CHAT: "AI_CHAT",
    AI_SEARCH: "AI_SEARCH",

    AI_CAPTION: "AI_CAPTION",
    AI_SCRIPT: "AI_SCRIPT",
    AI_EDITOR: "AI_EDITOR",
    AI_THUMBNAILS: "AI_THUMBNAILS",

    AI_MARKETING: "AI_MARKETING",
    AI_CAMPAIGNS: "AI_CAMPAIGNS",
    AI_ANALYTICS: "AI_ANALYTICS",

    // MONETIZATION

    ADS: "ADS",
    AFFILIATE: "AFFILIATE",
    TIPS: "TIPS",
    GIFTS: "GIFTS",

    CREATOR_SUBSCRIPTIONS: "CREATOR_SUBSCRIPTIONS",
    BUSINESS_SUBSCRIPTIONS: "BUSINESS_SUBSCRIPTIONS",

    DIGITAL_PRODUCTS: "DIGITAL_PRODUCTS",
    COURSES: "COURSES",

    BRAND_DEALS: "BRAND_DEALS",

    // ADMIN

    ADMIN_PANEL: "ADMIN_PANEL",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_PAYMENTS: "MANAGE_PAYMENTS"
};

const BASE = [

    FEATURES.VIEW_FEED,
    FEATURES.VIEW_REELS,
    FEATURES.VIEW_STORIES,
    FEATURES.VIEW_PODCASTS,
    FEATURES.VIEW_WATCH_PARTIES,
FEATURES.ADVERTISEMENT_VIEW,
    FEATURES.VIEW_CREATOR_HUB,
    FEATURES.VIEW_BUSINESS_HUB,
     FEATURES.VIEW_PODCASTS_HUB,
FEATURES.VIEW_EPISODES_HUB,

    FEATURES.VIEW_MARKETPLACE,

    FEATURES.VIEW_WALLET,
    FEATURES.VIEW_MONETIZATION,

    FEATURES.SEARCH,
    FEATURES.DISCOVER,
    FEATURES.TRENDING,

    FEATURES.CREATE_POST,
    FEATURES.EDIT_POST,
    FEATURES.DELETE_POST,

    FEATURES.CREATE_REEL,
    FEATURES.EDIT_REEL,
    FEATURES.DELETE_REEL,
FEATURES.APPLICATION_VIEW,
    FEATURES.CREATE_STORY,
    FEATURES.EDIT_STORY,
    FEATURES.DELETE_STORY,
   
    FEATURES.COMMENT,
    FEATURES.LIKE,
    FEATURES.SHARE,

    FEATURES.POST_REPORT,
    FEATURES.POST_SAVE,

    FEATURES.FOLLOW,
FEATURES.SEND_FRIEND_REQUEST,
FEATURES.ACCEPT_FRIEND_REQUEST,
FEATURES.REJECT_FRIEND_REQUEST,
FEATURES.CANCEL_FRIEND_REQUEST,
FEATURES.UNFRIEND,
     FEATURES.MEDIA_UPLOAD,
FEATURES.APPLICATION_CREATE,
    FEATURES.CONVERSATION_READ,
FEATURES.CONVERSATION_CREATE,
    FEATURES.MARKETPLACE_BUY,

    FEATURES.AI_CHAT,
    FEATURES.AI_SEARCH,

    FEATURES.WALLET

];



const FREE_MEMBER = [
    ...BASE,
    FEATURES.TIPS,
    FEATURES.GIFTS,
    FEATURES.AFFILIATE
];

const MEMBER_BASIC = [
    ...BASE,
    FEATURES.TIPS,
    FEATURES.GIFTS,
    FEATURES.AFFILIATE
];

const MEMBER_PLUS = [
    ...BASE,
    FEATURES.TIPS,
    FEATURES.GIFTS,
    FEATURES.AFFILIATE
];

const FREE_CREATOR = [
    ...BASE,
    FEATURES.CREATOR_PROFILE,
    FEATURES.ADS,
    FEATURES.CREATOR_SUBSCRIPTIONS,
    FEATURES.MARKETPLACE_CREATE,
    FEATURES.MARKETPLACE_SELL,
     FEATURES.CREATOR_HIRE_CREATE,
     FEATURES.PODCAST_CREATE,
     FEATURES.EPISODE_CREATE,
     FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
    FEATURES.SPONSORSHIP_APPLY,
FEATURES.APPLICATION_UPDATE
];

const CREATOR_BASIC = [
    ...FREE_CREATOR,
    FEATURES.CREATOR_STUDIO,
    FEATURES.CREATOR_ANALYTICS,
    FEATURES.CONTENT_SCHEDULER,
    FEATURES.LIVE_720,
    FEATURES.AFFILIATE,
    FEATURES.MARKETPLACE_CREATE,
    FEATURES.MARKETPLACE_SELL,
    FEATURES.CREATOR_HIRE_CREATE,
    FEATURES.PODCAST_CREATE,
    FEATURES.EPISODE_CREATE,
     FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
FEATURES.SPONSORSHIP_APPLY,
FEATURES.APPLICATION_UPDATE
];

const CREATOR_PLUS = [
    ...CREATOR_BASIC,
    FEATURES.AI_CAPTION,
    FEATURES.AI_SCRIPT,
    FEATURES.AI_THUMBNAILS,
    FEATURES.AI_EDITOR,
    FEATURES.LIVE_1080,
    FEATURES.DIGITAL_PRODUCTS,
    FEATURES.BRAND_DEALS,
    FEATURES.MARKETPLACE_CREATE,
    FEATURES.MARKETPLACE_SELL,
    FEATURES.CREATOR_HIRE_CREATE,
    FEATURES.PODCAST_CREATE,
    FEATURES.EPISODE_CREATE,
     FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
    FEATURES.SPONSORSHIP_APPLY,
    FEATURES.APPLICATION_UPDATE
    
];

const CREATOR_PRO = [
    ...Object.values(FEATURES)
];

const FREE_BUSINESS = [
    ...BASE,
    FEATURES.BUSINESS_PROFILE,
    FEATURES.PRODUCTS,
    FEATURES.SERVICES,
    FEATURES.MARKETPLACE_SELL,
FEATURES.PODCAST_CREATE,
FEATURES.EPISODE_CREATE,
    FEATURES.MARKETPLACE_CREATE,
    FEATURES.BUSINESSFIND_CREATE,
     FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
     FEATURES.ADVERTISEMENT_CREATE,
    FEATURES.SPONSORSHIP_CREATE,
    FEATURES.SPONSORSHIP_VIEW_APPLICATIONS,
     FEATURES.SPONSORSHIP_ACCEPT,
FEATURES.SPONSORSHIP_REJECT,
    FEATURES.APPLICATION_UPDATE
];

const BUSINESS_BASIC = [
    ...FREE_BUSINESS,
    FEATURES.BUSINESS_STUDIO,
    FEATURES.ORDERS,
    FEATURES.INVENTORY,
    FEATURES.CRM,
    FEATURES.LIVE_720,
    FEATURES.MARKETPLACE_SELL,
    FEATURES.PODCAST_CREATE,
    FEATURES.EPISODE_CREATE,
    FEATURES.MARKETPLACE_CREATE,
     FEATURES.BUSINESSFIND_CREATE,
      FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
    FEATURES.SPONSORSHIP_CREATE,
     FEATURES.ADVERTISEMENT_CREATE,
     FEATURES.SPONSORSHIP_VIEW_APPLICATIONS,
      FEATURES.SPONSORSHIP_ACCEPT,
FEATURES.SPONSORSHIP_REJECT,
     FEATURES.APPLICATION_UPDATE
];

const BUSINESS_PRO = [
    ...BUSINESS_BASIC,
    FEATURES.AI_MARKETING,
    FEATURES.AI_CAMPAIGNS,
    FEATURES.AI_ANALYTICS,
    FEATURES.BUSINESS_ANALYTICS,
    FEATURES.LOYALTY,
    FEATURES.COUPONS,
    FEATURES.LIVE_1080,
    FEATURES.MARKETPLACE_SELL,
    FEATURES.PODCAST_CREATE,
    FEATURES.EPISODE_CREATE,
    FEATURES.MARKETPLACE_CREATE,
     FEATURES.BUSINESSFIND_CREATE,
      FEATURES.PODCAST_DELETE,
    FEATURES.EPISODE_DELETE,
    FEATURES.SPONSORSHIP_CREATE,
    FEATURES.ADVERTISEMENT_CREATE,
    FEATURES.SPONSORSHIP_VIEW_APPLICATIONS,
    FEATURES.SPONSORSHIP_ACCEPT,
FEATURES.SPONSORSHIP_REJECT,
    FEATURES.APPLICATION_UPDATE
];

const BUSINESS_ENTERPRISE = [
    ...Object.values(FEATURES)
];




const PERMISSIONS = {
    FREE_MEMBER,
    MEMBER_BASIC,
    MEMBER_PLUS,

    FREE_CREATOR,
    CREATOR_BASIC,
    CREATOR_PLUS,
    CREATOR_PRO,

    FREE_BUSINESS,
    BUSINESS_BASIC,
    BUSINESS_PRO,
    BUSINESS_ENTERPRISE
};

class PermissionRules {

   static can(user, permission) {

    // ADMIN BYPASS
    if (
        user.role === "admin" ||
        user.role === "superadmin"
    ) {
        return {
            allowed: true,
            code: "ADMIN_BYPASS"
        };
    }

    console.log("USER =", user);
    console.log("REQUESTED =", permission);
    console.log("PLAN =", user.subscriptionPlan);

    const permissions =
        PERMISSIONS[user.subscriptionPlan] || [];

    console.log("PLAN PERMISSIONS =", permissions);

    return {
        allowed: permissions.includes(permission),
        code: permissions.includes(permission)
            ? "OK"
            : "PERMISSION_DENIED"
    };

}

static check(user, permission) {

    // ADMIN BYPASS
    if (
        user.role === "admin" ||
        user.role === "superadmin"
    ) {
        return {
            allowed: true
        };
    }

    // continue checking plan permissions...
}

    static hasPermission(user, feature) {
        return this.can(user, feature).allowed;
    }

    static require(user, feature) {
        const result = this.can(user, feature);

        if (!result.allowed)
            throw new Error(result.code);

        return true;
    }

    static getPermissions(plan) {
        return PERMISSIONS[plan] || [];
    }

}

module.exports = {

  
  PermissionRules

};